# Generated by Django 4.2.4 on 2024-05-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTRADE', '0016_newsprediction_delete_news_predictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrediction',
            fields=[
                ('symbol', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('next_close_prediction', models.IntegerField(default=0)),
                ('next_week_prediction', models.IntegerField(default=0)),
                ('next_biweek_prediction', models.IntegerField(default=0)),
                ('next_triweek_prediction', models.IntegerField(default=0)),
                ('next_month_prediction', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'predictions',
                'managed': False,
            },
        ),
    ]
