# Generated by Django 4.2.4 on 2024-05-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTRADE', '0017_historicalprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReportPrediction',
            fields=[
                ('symbol', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('prediction', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'financial_report_predictions',
                'managed': False,
            },
        ),
    ]
