# Generated by Django 4.2.4 on 2024-01-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTRADE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plans',
            field=models.TextField(blank=True),
        ),
    ]
