# Generated by Django 4.2.4 on 2024-02-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTRADE', '0010_rename_close_stockdata_close_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockData',
        ),
    ]
