# Generated by Django 4.2.4 on 2024-01-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTRADE', '0002_userprofile_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.TextField(blank=True),
        ),
    ]
