# Generated by Django 4.2.4 on 2024-02-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTRADE', '0008_stock_stockdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='close_price',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='dividends',
            new_name='Dividends',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='high_price',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='low_price',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='open_price',
            new_name='Open',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='stock_splits',
            new_name='Stock_Splits',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='volume',
            new_name='Volume',
        ),
    ]
