# Generated by Django 4.2.4 on 2024-02-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTRADE', '0009_rename_close_price_stockdata_close_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='Close',
            new_name='close_price',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='Dividends',
            new_name='dividends',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='High',
            new_name='high_price',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='Low',
            new_name='low_price',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='Open',
            new_name='open_price',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='Stock_Splits',
            new_name='stock_splits',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='Volume',
            new_name='volume',
        ),
    ]
